name: 🐛 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - mrjones2014
body:
  - type: checkboxes
    id: similar-issues
    attributes:
      label: Similar Issues
      options:
        - label: Before filing, I have searched for similar issues.
          required: true
    validations:
      required: true
  - type: textarea
    id: nvim-version
    attributes:
      label: Neovim Version
      description: "`nvim --version` output, please use a code block"
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    validations:
      required: true
    attributes:
      label: Steps to Reproduce
      value: |
        1. Open finder
        2. Select an item
        3. ...
        4. Profit?
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: min-config
    attributes:
      label: Minimal Configuration to Reproduce
      description: "MINIMAL `init.lua` or `init.vim` to reproduce, please use a code fence with `lua` syntax specified (e.g. ```lua). All unrelated config and plugins should be removed. See [minimal init.lua template](https://github.com/mrjones2014/legendary.nvim/discussions/93)"
      value: |
        ```lua
        local root = vim.fn.fnamemodify('./.repro', ':p')

        -- set stdpaths to use .repro
        for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
          vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
        end

        -- bootstrap lazy
        local lazypath = root .. '/plugins/lazy.nvim'
        if not vim.loop.fs_stat(lazypath) then
          vim.fn.system({
            'git',
            'clone',
            '--filter=blob:none',
            '--single-branch',
            'https://github.com/folke/lazy.nvim.git',
            lazypath,
          })
        end
        vim.opt.runtimepath:prepend(lazypath)

        -- install plugins
        local plugins = {
          -- do not remove the colorscheme! it makes testing nicer
          'folke/tokyonight.nvim',
          'mrjones2014/smart-splits.nvim',
          -- add any other pugins here
        }

        require('lazy').setup(plugins, {
          root = root .. '/plugins',
        })

        require('smart-splits').setup({
          -- add any options here
        })

        -- recommended mappings
        -- resizing splits
        -- these keymaps will also accept a range,
        -- for example `10<A-h>` will `resize_left` by `(10 * config.default_amount)`
        vim.keymap.set('n', '<A-h>', require('smart-splits').resize_left)
        vim.keymap.set('n', '<A-j>', require('smart-splits').resize_down)
        vim.keymap.set('n', '<A-k>', require('smart-splits').resize_up)
        vim.keymap.set('n', '<A-l>', require('smart-splits').resize_right)
        -- moving between splits
        vim.keymap.set('n', '<C-h>', require('smart-splits').move_cursor_left)
        vim.keymap.set('n', '<C-j>', require('smart-splits').move_cursor_down)
        vim.keymap.set('n', '<C-k>', require('smart-splits').move_cursor_up)
        vim.keymap.set('n', '<C-l>', require('smart-splits').move_cursor_right)
        -- swapping buffers between windows
        vim.keymap.set('n', '<leader><leader>h', require('smart-splits').swap_buf_left)
        vim.keymap.set('n', '<leader><leader>j', require('smart-splits').swap_buf_down)
        vim.keymap.set('n', '<leader><leader>k', require('smart-splits').swap_buf_up)
        vim.keymap.set('n', '<leader><leader>l', require('smart-splits').swap_buf_right)

        -- add anything else here
        vim.opt.termguicolors = true
        -- do not remove the colorscheme! it makes testing nicer
        vim.cmd([[colorscheme tokyonight]])
        ```
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output from :LegendaryLog
      description: Please run `:LegendaryLog` and paste the log output between the code fences (triple back ticks) below.
      value: |
        <details>
        <summary><code>:LegendaryLog</code> output (click to expand)</summary>

        ```

        ```
        </details>
  - type: textarea
    id: details
    attributes:
      label: Additional Details and/or Screenshots
