-- commented out ones need a way to get input after selecting
local M = {
  builtins = {
    { ':enew', description = 'New untitled document', builtin = true },
    { ':sp', description = 'Split open (horizontal)', builtin = true },
    { ':vs', description = 'Split open (vertical)', builtin = true },
    { '<C-o><C-o>', description = 'Reopen last opened file', builtin = true },
    { 'gx', description = 'Open with external app', builtin = true },
    { ':bd', description = 'Close file', builtin = true },
    { ':%bd', description = 'Close all', builtin = true },
    { ':w', description = 'Save', builtin = true },
    { ':up', description = 'Save (only if modified)', builtin = true },
    { ':sav {filename}', description = 'Save as', builtin = true, unfinished = true },
    { ':wa', description = 'Save all', builtin = true },
    { ':w!', description = 'Save read-only file', builtin = true },
    { ':mks', description = 'Save session', builtin = true },
    { ':so Session.vim', description = 'Restore session', builtin = true },
    { ':e', description = 'Reload file from disk', builtin = true },
    { ':e!', description = 'Revert to last saved', builtin = true },
    { ':TOhtml', description = 'Convert buffer to HTML', builtin = true },
    { ':hardcopy', description = 'Print document', builtin = true },
    { ':q', description = 'Quit (window)', builtin = true },
    { ':x', description = 'Save and quit (window)', builtin = true },
    { 'ZZ', description = 'Save and quit (window)', builtin = true },
    { ':q!', description = 'Quit without saving', builtin = true },
    { 'ZQ', description = 'Quit without saving', builtin = true },
    { ':xa', description = 'Save all and exit Vim', builtin = true },
    { ':qa!', description = 'Exit Vim without saving', builtin = true },

    { '<Esc>', description = 'Back to normal mode', builtin = true },
    { '<C-c>', description = 'Cancel command/operation', builtin = true },
    { 'i', description = 'Insert at cursor pos.', builtin = true },
    { 'a', description = 'Append after cursor', builtin = true },
    { 'I', description = 'Insert at start of line', builtin = true },
    { 'A', description = 'Append at end of line', builtin = true },
    { 'o', description = 'Open new line below', builtin = true },
    { 'O', description = 'Open new line above', builtin = true },
    -- { 'r{c}', description = 'Replace character with {c}', builtin = true },
    { 'R', description = 'Replace mode/overwrite', builtin = true },
    { 'c', description = 'Change', builtin = true },
    { 'cc', description = 'Replace line', builtin = true },
    { '.', description = 'Repeat last command', builtin = true },
    { 'u', description = 'Undo', builtin = true },
    { '<C-r>', description = 'Redo', builtin = true },
    { 'g+', description = 'Next text state', builtin = true },
    { 'g-', description = 'Prev text state', builtin = true },
    { 'd', description = 'Cut', builtin = true },
    -- { '"{r}d', description = 'Cut into register {r}', builtin = true },
    { '"*d', description = 'Cut into OS clipboard', builtin = true },
    -- { '{n}dd', description = 'Cut {n} lines', builtin = true },
    { 'D', description = 'Cut until EOL', builtin = true },
    -- { '{n}X', description = 'Cut {n} characters backwards', builtin = true },
    { ':%d', description = 'Cut all', builtin = true },
    { 'y', description = 'Copy', builtin = true },
    -- { '"{r}y', description = 'Copy into register {r}', builtin = true },
    { '"*y', description = 'Copy into OS clipboard', builtin = true },
    { 'yy', description = 'Copy current line', builtin = true },
    { 'y$', description = 'Copy until EOL', builtin = true },
    { ':%y', description = 'Copy all', builtin = true },
    { 'p', description = 'Paste after cursor', builtin = true },
    { 'P', description = 'Paste before cursor', builtin = true },
    -- { '"{r}p', description = 'Paste from register {r}', builtin = true },
    -- { '<C-r>{r}', description = 'Paste from register {r}', builtin = true },
    { '"*p', description = 'Paste from OS clipboard', builtin = true },
    { ']p', description = 'Paste after and align', builtin = true },
    { ']P', description = 'Paste before and align', builtin = true },
    { 'v', description = 'Visual mode (select)', builtin = true },
    { 'V', description = 'Linewise visual mode', builtin = true },
    { '<C-v>', description = 'Block visual mode', builtin = true },
    -- { '<C-v>{Move}I', description = 'Insert in selected lines', builtin = true },
    -- { '<C-v>{Move}A', description = 'Append to selected lines', builtin = true },
    -- { '<C-v>{Move}c', description = 'Change in selected lines', builtin = true },
    -- { '<C-v>{Move}x', description = 'Delete in selected lines', builtin = true },
    { 'gv', description = 'Reselect visual', builtin = true },
    { 'ggVG', description = 'Select all', builtin = true },
    { '<C-w>', description = 'Delete previous word', builtin = true },
    { '<C-u>', description = 'Erase line before cursor', builtin = true },
    -- { 'q{r}', description = 'Record macro into register {r}', builtin = true },
    { 'q', description = 'Stop recording macro', builtin = true },
    -- { '@{r}', description = 'Run recorded macro in register {r}', builtin = true },
    { '@@', description = 'Repeat last macro', builtin = true },
    { '@:', description = 'Repeat last Ex command', builtin = true },
    { ':bufdo {Cmd}', description = 'Run {Cmd} in all buffers', builtin = true, unfinished = true },

    { 'aw', description = 'Around word', builtin = true },
    { 'iw', description = 'Inside word', builtin = true },
    { 'aW', description = 'Around WORD', builtin = true },
    { 'iW', description = 'Inside WORD', builtin = true },
    { 'as', description = 'Around sentence', builtin = true },
    { 'is', description = 'Inside sentence', builtin = true },
    { 'ap', description = 'Around paragraph', builtin = true },
    { 'ip', description = 'Inside paragraph', builtin = true },
    { 'a( , ab', description = 'Around parentheses', builtin = true },
    { 'i( , ib', description = 'Inside parentheses', builtin = true },
    { 'a[', description = 'Around brackets', builtin = true },
    { 'i[', description = 'Inside brackets', builtin = true },
    { 'a{ , zB', description = 'Around braces', builtin = true },
    { 'i{ , iB', description = 'Inside braces', builtin = true },
    { 'at', description = 'Around (XML) tags', builtin = true },
    { 'it', description = 'Inside (XML) tags', builtin = true },
    { 'a<', description = 'Around < and >', builtin = true },
    { 'i<', description = 'Inside < and >', builtin = true },
    { 'a"', description = 'Around double quotes', builtin = true },
    { 'i"', description = 'Inside double quotes', builtin = true },
    { "a'", description = 'Around simple quotes', builtin = true },
    { "i'", description = 'Inside simple quotes', builtin = true },
    { 'a`', description = 'Around backticks', builtin = true },
    { 'i`', description = 'Inside backticks', builtin = true },

    { 'gU', description = 'Change to uppercase', builtin = true },
    { 'gu', description = 'Change to lowercase', builtin = true },
    { 'gUU', description = 'Uppercase line', builtin = true },
    { 'guu', description = 'Lowercase line', builtin = true },
    { 'U', description = 'Change to uppercase', builtin = true },
    { 'u', description = 'Change to lowercase', builtin = true },
    { '~', description = 'Toggle case', builtin = true },
    { '~', description = 'Toggle case', builtin = true },
    { '>', description = 'Indent (. to repeat)', builtin = true },
    { '<', description = 'Unindent (. to repeat)', builtin = true },
    { '=', description = 'Reindent', builtin = true },
    { '>>', description = 'Indent line (. repeats)', builtin = true },
    { '<<', description = 'Unindent (. repeats)', builtin = true },
    { '==', description = 'Reindent line', builtin = true },
    { '<C-t>', description = 'Indent line (insert mode)', builtin = true },
    { '<C-d>', description = 'Unindent line (insert mode)', builtin = true },
    { 'gq', description = 'Hard-wrap (cursor moves)', builtin = true },
    { 'gw', description = 'Hard-wrap (cursor stays)', builtin = true },
    { 'gww', description = 'Format current line', builtin = true },
    { 'J', description = 'Join with next line', builtin = true },
    { 'gJ', description = 'Join next line preserve spaces', builtin = true },
    { ':set noet', description = 'Use hard tabs', builtin = true },
    { ':set et', description = 'Use soft tabs (spaces)', builtin = true },
    { ':retab', description = "Detab (needs 'et' on)                ", builtin = true },
    { ':retab!', description = "Entab (needs 'et' off)               ", builtin = true },
    { ':set tw={n}', description = 'Set text width to {n}', builtin = true, unfinished = true },
    { ':sort', description = 'Sort selected lines', builtin = true },
    { ':sort u', description = 'Sort+remove duplicates', builtin = true },
    { ':norm @{r}', description = 'Run macro in reg {r} for each line', builtin = true, unfinished = true },
    -- { ':g/{P}/{Cmd}', description = 'Run {Cmd} on lines matching {P}', builtin = true },
    { '<C-n>', description = 'Autocomplete (search forward)', builtin = true },
    { '<C-p>', description = 'Autocomplete (search backwards)', builtin = true },
    { '<C-x><C-o>', description = 'Omnicomplete', builtin = true },
    { '<C-x><C-l>', description = 'Line autocomplete', builtin = true },
    -- { '<C-k>{c}{c}', description = 'Insert digraph', builtin = true },
    { '<C-r>=', description = 'Insert calculated expr.', builtin = true },
    { '<C-a>', description = 'Increment number', builtin = true },
    { '<C-x>', description = 'Decrement number', builtin = true },

    { ':setl spell!', description = 'Toggle spell checking', builtin = true },
    { ']s', description = 'To next misspelled word', builtin = true },
    { '[s', description = 'To prev misspelled word', builtin = true },
    { 'z=', description = 'Suggest corrections (normal mode)', builtin = true },
    { '<C-x>s', description = 'Suggest corrections (insert mode)', builtin = true },
    { 'zg', description = 'Permanently mark as correct', builtin = true },
    { 'zug', description = 'Undo mark as correct', builtin = true },
    { 'zG', description = 'Temporarily mark as correct', builtin = true },
    { 'zw', description = 'Permanently mark as incorrect', builtin = true },
    { 'zuw', description = 'Undo mark as incorrect', builtin = true },
    { 'zW', description = 'Temporarily mark as incorrect', builtin = true },

    { '<C-f>', description = 'Scroll down a page', builtin = true },
    { '<C-b>', description = 'Scroll up a page', builtin = true },
    { '<C-d>', description = 'Scroll down half a page', builtin = true },
    { '<C-u>', description = 'Scroll up half a page', builtin = true },
    { '<C-e>', description = 'Scroll down a bit', builtin = true },
    { '<C-y>', description = 'Scroll up a bit', builtin = true },
    { 'zl', description = 'Scroll horizontally right', builtin = true },
    { 'zh', description = 'Scroll horizontally left', builtin = true },
    { 'zL', description = 'Scroll horizontally half a screen', builtin = true },
    { 'zH', description = 'Scroll horizontally half a screen', builtin = true },
    { 'zt', description = 'Scroll line to top', builtin = true },
    { 'zb', description = 'Scroll to bottom', builtin = true },
    { 'zz', description = 'Scroll to center', builtin = true },
    { ':setl wrap!', description = 'Toggle soft-wrapping', builtin = true },
    { ':setl cc={n}', description = 'Page guide at column {n}', builtin = true, unfinished = true },
    { ':setl cc=', description = 'No page guide', builtin = true },
    { ':setl nu!', description = 'Toggle line numbers', builtin = true },
    { ':setl rnu!', description = 'Toggle relative line numbers', builtin = true },
    { ':setl list!', description = 'Toggle invisibles', builtin = true },
    { 'zR', description = 'Unfold all', builtin = true },
    { ':ls', description = 'Show files', builtin = true },
    { ':b <Tab>', description = 'Edit buffer (autocomplete)', builtin = true },
    { ':b{n}', description = 'Edit buffer {n}', builtin = true, unfinished = true },
    { '<C-^>', description = 'Edit last edited file', builtin = true },
    { ':bn', description = 'Edit next buffer', builtin = true },
    { ':bp', description = 'Edit prev buffer', builtin = true },
    { ':prev', description = 'Edir prev in arg list', builtin = true },
    { ':next', description = 'Edir next in arg list', builtin = true },
    { '<C-g>', description = 'Get file info', builtin = true },
    { 'ga', description = 'Character info', builtin = true },
    { 'gf', description = 'Go to file under cursor', builtin = true },
    { 'g<C-g>', description = 'Line/word/char count', builtin = true },
    { ':setl cul!', description = 'Toggle cursorline', builtin = true },
    { ':setl hls!', description = 'Toggle search highlight', builtin = true },
    { 'g%', description = 'Cycle match groups (eg. if,else,end) ', builtin = true },

    { ':set ic!', description = 'Toggle ignore case', builtin = true },
    { '/{P}', description = 'Search forward for {P}', builtin = true, unfinished = true },
    { '?{P}', description = 'Search backward for {P}', builtin = true, unfinished = true },
    { 'n', description = 'Go to next match', builtin = true },
    { 'N', description = 'Go to previous match', builtin = true },
    { 'gn', description = 'Select up to next match', builtin = true },
    { 'gN', description = 'Select up to prev match', builtin = true },
    { '*', description = 'Search word under cursor backward', builtin = true },
    { '#', description = 'Search word under cursor forward', builtin = true },
    { '<C-G>', description = 'Go to next match during search', builtin = true },
    { '<C-T>', description = 'Go to previous match during search', builtin = true },
    -- { ':s/{P}/{P}/g', description = 'Find and replace', builtin = true },
    -- { ':s/{P}/{P}/gc', description = 'Find and replace confirm', builtin = true },
    -- { ':%s/{P}/{P}/g', description = 'Find and replace all', builtin = true },
    { ':copen', description = 'Open quickfix', builtin = true },
    { ':cp', description = 'Prev in quickfix list', builtin = true },
    { ':cn', description = 'Next in quickfix list', builtin = true },
    { ':cclose', description = 'Close quickfix', builtin = true },
    { ':lopen', description = 'Open location list', builtin = true },
    { ':lp', description = 'Prev in location list', builtin = true },
    { ':lne', description = 'Next in location list', builtin = true },
    { ':lclose', description = 'Close location list', builtin = true },
    { '<C-n>', description = 'Next command (command mode)', builtin = true },
    { '<C-p>', description = 'Prev command (command mode)', builtin = true },
    { 'q:', description = 'Browse command history', builtin = true },
    { 'q/', description = 'Browse search patterns', builtin = true },
    { ':diffthis', description = 'Use this file for diff', builtin = true },
    { ':diffoff!', description = 'Exit diff mode', builtin = true },
    { ':diffupdate', description = 'Re-scan files for diffs', builtin = true },
    { ']c', description = 'Next difference', builtin = true },
    { '[c', description = 'Prev difference', builtin = true },
    { 'dp', description = 'Diff put', builtin = true },
    { 'do', description = 'Diff obtain', builtin = true },
    { ':diffget', description = 'Get differences', builtin = true },
    { ':diffput', description = 'Put differences', builtin = true },

    { 'h', description = 'Left', builtin = true },
    { 'l', description = 'Right', builtin = true },
    { 'k', description = 'Up', builtin = true },
    { 'j', description = 'Down', builtin = true },
    { 'gk', description = 'Up (honor soft-wrapping)', builtin = true },
    { 'gj', description = 'Down (honor soft-wrapping)', builtin = true },
    { 'w', description = 'Start of next word', builtin = true },
    { 'b', description = 'Start of prev word', builtin = true },
    { 'e', description = 'End of next word', builtin = true },
    { 'ge', description = 'End of prev word', builtin = true },
    { 'W', description = 'Start of next WORD', builtin = true },
    { 'B', description = 'Start of prev WORD', builtin = true },
    { 'E', description = 'End of next WORD', builtin = true },
    { 'gE', description = 'End of prev WORD', builtin = true },
    { '0', description = 'Start of line', builtin = true },
    { '$', description = 'End of line', builtin = true },
    { '^', description = 'This line 1st non-blank', builtin = true },
    { '+', description = 'Next line 1st non-blank', builtin = true },
    { '-', description = 'Prev line 1st non-blank', builtin = true },
    { 'gg', description = 'First line', builtin = true },
    { 'G', description = 'Last line', builtin = true },
    -- { 'f{c}', description = 'Next {c} in this line', builtin = true },
    -- { 't{c}', description = 'Just before next {c}', builtin = true },
    -- { 'F{c}', description = 'Prev {c} in this line', builtin = true },
    -- { 'T{c}', description = 'Just after prev {c}', builtin = true },
    { ';', description = 'Repeat f/t/F/T forward', builtin = true },
    { ',', description = 'Repeat f/t/F/T backward', builtin = true },
    { 'g;', description = 'Prev pos in change list', builtin = true },
    { 'g,', description = 'Next pos in change list', builtin = true },
    { ':{n}', description = 'Go to line {n}', builtin = true, unfinished = true },
    -- { '{n}|', description = 'Go to column {n}', builtin = true },
    -- { '{n}G', description = 'Jump to line {n}', builtin = true },
    { '}', description = 'Jump to next blank line', builtin = true },
    { '{', description = 'Jump to prev blank line', builtin = true },
    { '[{', description = 'Jump to begin of block', builtin = true },
    { ']}', description = 'Jump to end of block', builtin = true },
    { ')', description = 'Jump to end of sentence', builtin = true },
    { '(', description = 'Jump to beg. of sentence', builtin = true },
    { ']]', description = 'Jump to end of section', builtin = true },
    { '[[', description = 'Jump to beg. of section', builtin = true },
    { 'H', description = 'Jump to top of window', builtin = true },
    { 'M', description = 'Jump to middle', builtin = true },
    { 'L', description = 'Jump to bottom', builtin = true },
    { '%', description = 'Jump to matching delim', builtin = true },
    { ':tag [tagname]', description = 'Jump to specified tag', builtin = true, unfinished = true },
    { '<C-t>', description = 'Jump to older tag', builtin = true },
    { '<C-]>', description = 'Jump to tag definition', builtin = true },
    { 'g]', description = 'Jump to tag definition, show choices ', builtin = true },
    { 'g<C-]>', description = 'Jump or show choices', builtin = true },
    { ':tn', description = 'To next matching tag', builtin = true },
    { ':tp', description = 'To prev matching tag', builtin = true },
    -- { 'm{c}', description = 'Set mark {c}', builtin = true },
    -- { '`{c}', description = 'Jump to mark at {c}', builtin = true },
    { ':marks', description = 'View all marks', builtin = true },
    { ':delmarks {mark}', description = 'Remove marks', builtin = true, unfinished = true },
    { 'gd', description = 'Jump to definition', builtin = true },
    { '<C-o>', description = 'To prev jump position', builtin = true },
    { '<C-i>', description = 'To next jump position', builtin = true },
    { 'gi', description = 'Go to last insertion and INSERT', builtin = true },

    { 'zj', description = 'Go to start of next fold', builtin = true },
    { 'zk', description = 'Go to end of previous fold', builtin = true },
    { 'zo', description = 'Open fold under cursor', builtin = true },
    { 'zO', description = 'Open all folds under cursor', builtin = true },
    { 'zc', description = 'Close fold under cursor', builtin = true },
    { 'zC', description = 'Close all folds under cursor', builtin = true },
    { 'za', description = 'Toggle fold under cursor', builtin = true },
    { 'zA', description = 'Toggle all folds under cursor', builtin = true },
    { 'zv', description = 'Open folds to show cursor line', builtin = true },
    { 'zM', description = 'Close all folds', builtin = true },
    { 'zR', description = 'Open all folds', builtin = true },
    { 'zm', description = 'Fold more', builtin = true },
    { 'zr', description = 'Fold less', builtin = true },
    { 'zx', description = 'Update folds', builtin = true },

    { ':new', description = 'New horizontal split', builtin = true },
    { '<C-w><C-n>', description = 'New horizontal split', builtin = true },
    { ':vnew', description = 'New vertical split', builtin = true },
    { '<C-w>c', description = 'Close window', builtin = true },
    { '<C-w><C-o>', description = 'Close inactive windows', builtin = true },
    { '<C-w>s', description = 'Split horizontally', builtin = true },
    { '<C-w><C-v>', description = 'Split vertically', builtin = true },
    { '<C-w><C-x>', description = 'Exchange windows', builtin = true },
    { '<C-w>K', description = 'Move to the very top', builtin = true },
    { '<C-w>J', description = 'Move to the very bottom', builtin = true },
    { '<C-w>L', description = 'Move to the far right', builtin = true },
    { '<C-w>H', description = 'Move to the far left', builtin = true },
    { ':ball', description = 'One window per file', builtin = true },
    { '<C-w><C-w>', description = 'Cycle through windows', builtin = true },
    { '<C-w><C-p>', description = 'Back to previous window', builtin = true },
    { '<C-w><C-h>', description = 'Edit window to the left', builtin = true },
    { '<C-w><C-j>', description = 'Edit window below', builtin = true },
    { '<C-w><C-k>', description = 'Edit window above', builtin = true },
    { '<C-w><C-l>', description = 'Edit window to the right', builtin = true },
    { '<C-w><C-t>', description = 'Edit top window', builtin = true },
    { '<C-w><C-b>', description = 'Edit bottom window', builtin = true },
    { '<C-w>=', description = 'All windows same size', builtin = true },
    { '<C-w>_', description = 'Maximize height', builtin = true },
    { '<C-w>|', description = 'Maximize width', builtin = true },
    { '<C-w>-', description = 'Decrease height', builtin = true },
    { '<C-w>+', description = 'Increase height', builtin = true },
    { '<C-w><', description = 'Decrease width', builtin = true },
    { '<C-w>>', description = 'Increase width', builtin = true },
    { ':windo {Cmd}', description = 'Execute {Cmd} in all windows', builtin = true, unfinished = true },

    { ':tabnew', description = 'New untitled tab', builtin = true },
    { ':tabe [file]', description = 'New/open in tab', builtin = true, unfinished = true },
    { 'gt', description = 'Next tab', builtin = true },
    { 'gT', description = 'Previous tab', builtin = true },
    -- { '{n}gt', description = 'Go to tab {n}', builtin = true },
    { ':tabc', description = 'Close tab', builtin = true },
    { ':tabo', description = 'Close all other tabs', builtin = true },
    { ':tabs', description = 'List tabs', builtin = true },
    { '<C-w>T', description = 'Move window to new tab', builtin = true },
    { ':tab ball', description = 'Open one tab per buffer', builtin = true },
    { ':tabdo {Cmd}', description = 'Execute {Cmd} in all tabs', builtin = true, unfinished = true },

    { '%:p', description = 'Full path', builtin = true },
    { '%:~', description = 'Relative to $HOME', builtin = true },
    { '%:.', description = 'Relative to current directory', builtin = true },
    { '%:t', description = 'Filename only (tail)', builtin = true },
    { '%:r', description = 'Remove last extension (get root)', builtin = true },
    { '%:e', description = 'Extension only', builtin = true },
    { '%:S', description = 'Escape special chars (use in shell)', builtin = true },
    -- { '%:s?pat?sub?', description = 'Substitute first', builtin = true },
    -- { '%:gs?pat?sub?', description = 'Substitute all', builtin = true },
    { '%:p:h', description = 'Get directory of file', builtin = true },

    { ':h [helptag]', description = 'Help', builtin = true, unfinished = true },
    { ':helpgrep {searchterm}', description = 'Help search', builtin = true },
    { ':h hitest.vim', description = 'Help on highlight test', builtin = true },
    { ':map [mapping]', description = 'View mappings', builtin = true, unfinished = true },
    { ':imap [mapping]', description = 'View Insert mode mappings', builtin = true, unfinished = true },
    { ':reg', description = 'View registers', builtin = true },
    { ':scr', description = 'List of sourced files', builtin = true },
    { ':digraphs', description = 'List of digraphs', builtin = true },
    { ':syn', description = 'List all syntax items', builtin = true },

    { ':pwd', description = 'Show current directory', builtin = true },
    { ':cd {dir}', description = 'Change directory', builtin = true, unfinished = true },
    { ':cd', description = 'Change to home directory', builtin = true },
    { ':echo {Var}', description = 'Show value of {Var}', builtin = true, unfinished = true },
    -- for this one we'd need to somehow put the cursor before the ? in the cmdline
    -- { ':set {Opt}?', description = 'Show value of option', builtin = true },
  },
}

function M.register_builtins()
  require('legendary.bindings').bind(M.builtins)
end

return M
